import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-awesome-slider/dist/styles.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "animate.css";
import "aos/dist/aos.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Solomon Bonney - Portfolio Website",
  description: "Generated by create next app",
  googleAdsenseAccount: "ca-pub-8714930201859650",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8714930201859650"
        crossOrigin="anonymous"
      ></script>
      <body className="body">
        <ToastContainer />
        {children}
      </body>
      <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
    </html>
  );
}
